HyperloopUPV-H8/ST-LIB

Inc/HALAL/Services/DigitalInput/DigitalInput.hpp, Inc/HALAL/Services/DigitalOutput/DigitalOutput.hpp, Src/HALAL/Services/DigitalInput/DigitalInput.cpp, Src/HALAL/Services/DigitalOutput/DigitalOutput.cpp
- The following variables have been changed to camel case:
- The following check has been added to each method to avoid unexpected behavior:
=> Fixed some errors in DigitalInput/Output

.cproject
Adds necessary include for working with the STLIB LOW.
For overwriting the .cproject check [this PR](https://github.com/HyperloopUPV-H8/ST-LIB/pull/21).
=> add STLIB LOW includes

Inc/HALAL/Models/PinModel/Pin.hpp, Inc/HALAL/Services/EXTI/EXTI.hpp, Src/HALAL/Models/PinModel/Pin.cpp, Src/HALAL/Models/Runes/Runes.cpp, Src/HALAL/Services/EXTI/EXTI.cpp
This PR implements the start function for the HALAL EXTI service and adds exti configuration for the Pin Start function. This replaces the MX_GPIO_INIT() for the external interrupt.
```
ExternalInterrupt::start();
ExternalInterrupt::turn_on(exti1);
```
=> add EXTI Start

Inc/HALAL/Models/PinModel/Pin.hpp, Inc/HALAL/Services/PWMservice/PWMservice.hpp, Src/HALAL/Models/PinModel/Pin.cpp, Src/HALAL/Models/Runes/Runes.cpp, Src/HALAL/Services/PWMservice/PWMservice.cpp
Necessary update for PWM init in order to work with multiple gpio ports. It also simplifies the design and the initdata constructor.
It works.
=> PWM Start update

Inc/HALAL/Models/Packets/RawPacket.hpp, Inc/HALAL/Services/Communication/UART/UART.hpp, Src/HALAL/Services/Communication/UART/UART.cpp
=> All UART init methods implemented 

Inc/HALAL/Models/Packets/Packet.hpp, Inc/HALAL/Models/Packets/PacketValue.hpp, Inc/ST-LIB.hpp, Src/HALAL/Services/Communication/Ethernet/UDP/DatagramSocket.cpp
This PR adds certain functionalities to Packet and PacketValue classes:
·Now Custom types can be sent and received with packets
·Now Dynamic Container Types can be sent and received with packets
>**Note**
>The sender can update the size of dynamic containers when building again a Packet but when receiving them the size received must be the same one as the last size sent, a way to bypass this is having all dynamic containers have a label before them indicating the size of the container, this is yet not implemented and will be further done if needed
Sintax for Packet Creation now looks like this:
Tests performed:
-Building Packet containing both Integral with factor PacketValues and dynamic container PacketValues, receiving the same Packet with new data and loading it:
**Code**:
```cpp …
```
=> Added extra features to Packets

Inc/HALAL/Services/CORDIC/CORDIC.hpp
Seems that the .hpp changes weren t correctly commited, so the library can t compile.
This hotfix repairs it and assures that the CORDIC class works properly (re tested all 6 methods with 3 values each).
The error was that the commit that changed the parameter size from int to int32_t affected the .cpp but not the .hpp, so each of them had different parameters
=> CORDIC hotfix

Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp, Src/ST-LIB_LOW/StateMachine/StateMachine.cpp
This PW reworks the State Machine to use cyclic actions using Time HALAL Service.
``` cpp
state_machine.add_cyclic_action_in_microseconds([&]() {
adc_value = ADC::get_value(adc1).value();
}, 700us ,on);
```
Both microseconds and milliseconds actions have been tested.
=> State Machine Rework

Inc/HALAL/Models/Packets/Packet.hpp, Inc/HALAL/Services/Communication/UART/UART.hpp, Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp, Src/HALAL/Models/Runes/Runes.cpp, Src/HALAL/Services/Communication/Ethernet/UDP/DatagramSocket.cpp, Src/HALAL/Services/Communication/UART/UART.cpp
- Added TIM guard in StateMachine
- Moved som code from .hpp to .cpp to avoid weird bugs
Se han arreglado los `printf` y simplicado su uso. Ahora forman parte del servicio de UART y se puede ver como utilizarlos a continuación.
```cpp
UART::set_up_printf(UART::uart3);
UART::start();
printf("123456789%s", endl);
fprintf(stderr, "Error xD!%s", endl);
```
Ya no hace falta configurar nada para hacerlos funcionar, por tanto el articulo sobre los printf ha quedado desactualizado. Se modificará lo antes posible.
=> General fixes and Printf Fix

.cproject, Drivers/CMSIS/Device/ST/STM32H7xx/Include/stm32h7xx.h, Drivers/CMSIS/Include/core_cm7.h, Drivers/CMSIS/Include/mpu_armv7.h, Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_ll_adc.h, Inc/HALAL/Models/TimerPeripheral/TimerPeripheral.hpp, Src/HALAL/Services/InputCapture/InputCapture.cpp
This PR corrects two warnings in the ST-LIB and silences the deprecated |= operator warning, which de-deprecated in C++23.
=> supress warnings

.settings/language.settings.xml, Inc/HALAL/Models/LowPowerTimer/LowPowerTimer.hpp, Src/HALAL/Models/LowPowerTimer/LowPowerTimer.cpp, Src/HALAL/Models/Runes/Runes.cpp, Src/HALAL/Services/ADC/ADC.cpp
This PR introduces the LPTIM init function inside the ADC init function, which overloads the HAL init.
```cpp
Pin::start();
MX_DMA_Init();
ADC::start();
MX_LPTIM1_Init();
MX_LPTIM2_Init();
MX_LPTIM3_Init();
```
```cpp
Pin::start();
MX_DMA_Init();
ADC::start();
```
It has been tested with the same testcase of the ADC, deleting the HAL inits and checking that it still works correctly
=> LPTIM INIT function

Src/HALAL/Services/DigitalInputService/DigitalInputService.cpp
Había un error en la clase DigitalInputService.cpp ya que se accedia a id_counter en inscribe sin inicializarlo. 
Los hpp y cpp son bastante simplones en su forma de funcionar, así que si al dar un valor inicial en el cpp a una variable del hpp **no se le indica explicitamente** que es la del hpp, lo que hace es crear una variable nueva con el mismo nombre en el cpp e inicializar esa _(En lugar de inicializar la del hpp)_.
Luego cuando la usas mas tarde, incluso sin indicarle explicitamente que es del hpp con DigitalInput:: ..., sigue usando la del hpp _(en lugar de la nueva que creo e inicializo)_, pero no esta inicializada. 
Osea se, que si haces:
```
#include "DigitalInputService/DigitalInputService.hpp"
uint8_t id_counter = 0;
uint8_t DigitalInput::inscribe(Pin& pin){ …
```
=> fixed id_counter instansialization

Inc/C++Utilities/CppUtils.hpp
Today I had a conflict in my PCB code. I use iota function, but the compiler conflicts between std::iota and std::views::iota. In order to prevent this and future errors, I think the best solution is to explicitly state which functions and types we are using from the STD library.
Having namespace usages in a global file is already a very dangerous practice for a static library and probably the best solution would be to explicitly put the using statements in the corresponding file, as it avoids possible lateral effects and it is more transparent for the reader, as it knows what resources are being used in the class. Still this is a design decision out of the scope of this PR.
For now, we can at least improve the library by not having `using namespace std;` and instead having the explicit …
=> explicit std usages

Inc/HALAL/HALAL.hpp, Inc/HALAL/Services/CORDIC/CORDIC.hpp, Inc/ST-LIB_LOW/Math/Math.hpp, Inc/ST-LIB_LOW/ST-LIB_LOW.hpp, Src/HALAL/Services/CORDIC/CORDIC.cpp, Src/ST-LIB_LOW/Math/Math.cpp
the tangent did a division by 0 on some arbitrary numbers that were out of the safe guard. Now it s tested for every possible bit value and it does not divide by 0 (and the sample results were as precise as expected)
the module on the negative limit didn t go inside of the handler for results higher than one, giving a less-than-one result.
using at max speed multiple different math functions without anything in between may cause the configuration to not be correctly applied and some of the results being aberrant. To be exact seems that cosine, sine, and tangent are affected. Maybe changing the CORDIC code to a single shot structure (math does only single shot anyway) could solve the issue.
=> math+cordic bug solving

Src/HALAL/Services/ADC/ADC.cpp
This PR adds this conditional clause in order to make ADC work
```cpp
if (adc_handle.Instance == ADC3) {
adc_handle.Init.DMAContinuousRequests = ENABLE;
} else {
adc_handle.Init.ConversionDataManagement = ADC_CONVERSIONDATA_DMA_CIRCULAR;
}
```
=> Fix ADC3 not working

Inc/HALAL/Services/Communication/UART/UART.hpp
Removed the include of the ST-LIB in the UART that caused a circular dependency. This change resolves #149.
=> Removed stlib include in UART

Inc/C++Utilities/CppUtils.hpp, Inc/ST-LIB_LOW/ErrorHandler/ErrorHandler.hpp, Src/ST-LIB_LOW/ErrorHandler/ErrorHandler.cpp
First we need to use `...` because `args...` needs atleast 1 parameter. Next we ned to use `##__VA_ARGS__` to pass the arguments list. The `##` is needed because in case the arguments list is empty will swallow the preceding comma.
```cpp
#define ErrorHandler(x, ...) do { ErrorHandlerModel::SetMetaData(__LINE__, __FUNCTION__, __FILE__); \
ErrorHandlerModel::ErrorHandlerTrigger(x, ##__VA_ARGS__);}while(0)
```
Now we need to change the method `ErrorHandlerModel::ErrorHandler(string format, Args.. args)` to `ErrorHandlerModel::ErrorHandlerTrigger(string format, ...)` to avoid redefinition due to de macro function and to accept an empty argument list.
```cpp
static void ErrorHandlerTrigger(string format, ...);
```
Inside the method we need to handle the variable list using `va_lists` and we …
=> Now only one parameter is necesary to call ErrorHandler

Inc/HALAL/Services/Communication/SPI/SPI.hpp
This PR allows you to pass SPI peripherals as function parameter
=> fix wrong private enum in SPI

Inc/HALAL/Services/ADC/ADC.hpp, Src/HALAL/Services/ADC/ADC.cpp, Src/ST-LIB_HIGH/Protections/Protection.cpp
This PR changes ADC name so it doesn't conflict with external libraries like the BMS code
=> change constant name to be less ambigous

Src/HALAL/HALAL.cpp, Src/HALAL/Services/Communication/Ethernet/Ethernet.cpp, Src/ST-LIB.cpp
Se ha arreglado lo que provocaba que el `Ethernet::start()` no funcionase.
El metodo `Ethernet::update()` sigue sin funcionar.
=> Fixed Ethernet start and inscribe methods

Inc/HALAL/Models/IPV4/IPV4.hpp, Inc/HALAL/Models/Packets/Order.hpp, Inc/HALAL/Models/Packets/Packet.hpp, Inc/HALAL/Models/Packets/PacketValue.hpp, Inc/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.hpp, Inc/HALAL/Services/Communication/Ethernet/TCP/Socket.hpp, Inc/HALAL/Services/Communication/Ethernet/UDP/DatagramSocket.hpp, Inc/ST-LIB_LOW/DigitalOutput/DigitalOutput.hpp, Src/HALAL/Models/IPV4/IPV4.cpp, Src/HALAL/Models/Packets/Packet.cpp, Src/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.cpp, Src/HALAL/Services/Communication/Ethernet/TCP/Socket.cpp, Src/HALAL/Services/Communication/Ethernet/UDP/DatagramSocket.cpp, Src/ST-LIB_LOW/StateMachine/StateMachine.cpp
This PR adds a rework to the Packet Models. Mainly it changes its focus such that it takes much more advantage of cache locality and optimizes overall number of instructions as well as compile time recursive calls, achieving an overall speed improvement of nearly 3000% in some cases and reducing compiled code size in up to 300%.
Now all Packets and Orders implement a common interface that can be used to store any type of Packet or order in a container of interface pointers.
The rework now adds two posible instantiation of Packets and Orders:
· Stack variants: They don't use almost any heap allocations at the cost of using templates, thus making it harder to store and manipulate if not done through interface pointers. Best for raw perfomance however compiled code is much heavier with this …
=> Packets rework and minor fixes

Inc/HALAL/Services/Time/Time.hpp, Src/HALAL/Services/Time/Time.cpp
This branch fixes the offset of low precision timers, which made set_timeout non working
=> fix low precision offset

Inc/C++Utilities/CppUtils.hpp, Inc/HALAL/Models/Concepts/Concepts.hpp, Inc/HALAL/Models/DataStructures/StackTuple.hpp, Inc/HALAL/Models/DataStructures/TemplatePackFilter.hpp, Inc/HALAL/Models/Packets/Packet.hpp, Inc/HALAL/Models/Packets/PacketValue.hpp
Created Separate Model for Concepts and Data Structures
Added Several new Data Structures and concepts:
·TemplatePackFilter : receives a Template Argument Pack and filters types that are equal to argument type, can be used to count how many types are of one type or as template to filter a template argument pack given a certain concept
·PackDerivesFrom concept: returns true if all types in a given template parameter pack inherit from a given type
·Callable: returns true if type is invokable
·Has Callable: returns true if a given template parameter pack has any invokable type in it
=> moved concepts and data_structures

Inc/ST-LIB_HIGH/Control/Blocks/Derivator.hpp, Inc/ST-LIB_HIGH/Control/Blocks/Integrator.hpp
initializing some control blocks output value to 0 to avoid undefined behaviour
=> Zero Initialization of Control Blocks

Inc/ST-LIB_HIGH/Protections/Notification.hpp, Inc/ST-LIB_HIGH/Protections/Protection.hpp, Inc/ST-LIB_HIGH/Protections/ProtectionManager.hpp, Inc/ST-LIB_HIGH/ST-LIB_HIGH.hpp, Src/HALAL/Services/Communication/SNTP/SNTP.cpp, Src/ST-LIB.cpp, Src/ST-LIB_HIGH/Protections/ProtectionManager.cpp, Src/ST-LIB_HIGH/ST-LIB_HIGH.cpp
Changes added:
Changed IP of SNTP to the actual server IP (tested)
Put enum of faultType into a namespace so the global space isn t polluted with enums that are not meant to be used there (like FAULT)
Made that when the protection handler goes to fault it first sends a packet with ID 0 to all sockets to get all boards into fault faster. (tested)
add Error as a part of protection handler (tested)
changed build of notification to add a 0x00 byte at the end as the last version of chango-gui needs it to differenciate a packet end. (chango works with it and doesn t without in v12)
For now the ProtectionManager sends this fast packet once when it forces the GeneralStateMachine into fault. There is also a method called propagate_fault for anyone that needs it, but if any other behaviour is …
=> protection manager changes

Inc/C++Utilities/CppUtils.hpp, Inc/HALAL/Models/IPV4/IPV4.hpp, Inc/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.hpp, Inc/ST-LIB_LOW/Communication/Server/Server.hpp, Inc/ST-LIB_LOW/ST-LIB_LOW.hpp, LWIP/Target/lwipopts.h, Src/HALAL/Models/IPV4/IPV4.cpp, Src/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.cpp, Src/HALAL/Services/Communication/Ethernet/TCP/Socket.cpp, Src/ST-LIB.cpp, Src/ST-LIB_LOW/Communication/Server/Server.cpp
added a new class called Server which acts as a multi client server on same port. 
It includes broadcast and simple logic for disconnects.
Also fixes a few ServerSocket and Socket bugs, and adds a new constructor for IPV4. 
the keepalive is yet to be implemented, and will be in another pull request. This one is already bloated enough.
multi connection server code (blinks when he receives a hello order, and sends one each second to all connections)
```
uint32_t data = 0;
DigitalOutput* connection_led;
DigitalOutput* message_led;
void tog() {
message_led->toggle();
}
int main(void)
{
connection_led = new DigitalOutput(PE1);
message_led = new DigitalOutput(PB14);
STLIB::start();
StackOrder<0> hello_order(100,tog);
Server computer_socket(IPV4("192.168.0.3"),30000); …
```
=> tcp server multiconnection

Inc/HALAL/Services/Time/Time.hpp, Src/HALAL/Services/Time/Time.cpp
We already had a timeout function that was very useful, but we might want to cancel that timeout for whatever reasons,
we can do it now,
Watch out:
`set_timeout `now returns an uint8_t which is the id of the alarm registered, if the map of cyclic actions was full it will return 255, 
The function calls the ErrorHandler, so it should be fine, but in order for it to compile it needs to return something, so beware if no StateMachine has been implemented and you have registered a lot of actions.
In order to enforce checking for the return value the attribute `[[nodiscard]]` has been used
=> Time::cancel_timeout feature

Inc/HALAL/HALAL.hpp, Inc/HALAL/Models/Packets/ForwardOrder.hpp
ForwardOrder, the callback has been removed.
Visibility of unused methods has been changed to private, compiler optimizes better with this.
Note that the can't be removed because Order is pure virtual.
The constructor takes in a normal order + the ServerSocket that should forward it, it takes it in as a reference so that it can never be null.
testing code, some more changes are needed to change the MAC addresses
The PWM does change on the oscilloscope.
```cpp
//#define CLIENT
#include "main.h"
#include "lwip.h"
#include "ST-LIB.hpp"
#include "Runes/Runes.hpp"
static_assert(HSE_VALUE==8'000'000);
uint16_t test_phase = 0;
float test_duty = 0;
DigitalOutput* d1;
PWM* test_with_payload;
void change_duty(){
test_with_payload->set_duty_cycle(test_duty);
}
using namespace std::chrono_literals; …
```
=> ForwardOrder

Inc/HALAL/Services/Communication/Ethernet/UDP/DatagramSocket.hpp
send is used in ServerSocket as a way to send raw data, while send_order is used to abstract that into sending the data of a full order.
On DatagramSocket send is not used to send raw data, but instead is the abstraction of that for the full send of a packet. This makes nomenclature inconsistent between two similar classes, so i changed it into send_packet.
=> Changed send function name on DatagramSocket

Inc/ST-LIB_LOW/StateMachine/StateOrder.hpp, Src/ST-LIB_LOW/StateMachine/StateOrder.cpp
Se han cambiado el tamaño de los vectores de uint8_t a uint16_t para hacerlos compatibles con el backend
=> State order fix

Src/HALAL/Services/Communication/SPI/SPI.cpp
ErrorHandler should only occur with serious issues, this doesn't qualify as one.
=> dont trigger ErrorHandler if SPI transmission fails

Inc/HALAL/Services/Communication/Ethernet/Ethernet.hpp, Inc/HALAL/Services/Communication/Ethernet/EthernetHelper.hpp, Src/HALAL/Services/Communication/Ethernet/Ethernet.cpp
Basic changes that need the template-project updates otherwise it doesn't compile.
This detection is way faster than waiting for keepalives, which I'm not sure if detected this kind of failure
=> Detect Ethernet cable disconnection

Inc/ST-LIB_LOW/ErrorHandler/ErrorHandler.hpp, Src/HALAL/Services/Communication/Ethernet/TCP/Socket.cpp, Src/ST-LIB_HIGH/Protections/ProtectionManager.cpp, Src/ST-LIB_LOW/ErrorHandler/ErrorHandler.cpp
As the title says.
Also, now the socket triggers ErrorHandler in any disconnection (same behaviour as the ServerSocket)
=> error handler spam solved. Now only sends once

Inc/HALAL/Services/Time/Time.hpp, Src/HALAL/Services/Time/Time.cpp
Lets you configure on runes what timer should be high, mid or global, or even disable them by putting nullptr on the respective pointer (or leaving the set empty for the high timers)
For any project that copied the template before this patch, it is needed to add on runes the next lines, on line 144:`
```
TIM_HandleTypeDef* Time::global_timer = &htim2;
set<TIM_HandleTypeDef*> Time::high_precision_timers = {&htim5, &htim24};
TIM_HandleTypeDef* Time::mid_precision_timer = &htim23;
```
This is the standard configuration used before this patch.
=> time config now working on runes

Inc/HALALMock/Models/PinModel/Pin.hpp, Inc/HALALMock/Services/PWM/DualPWM/DualPWM.hpp, Src/HALALMock/Services/PWM/DualPWM/DualPWM.cpp
Modified the DualPWM .cpp and .hpp so as to be used with the HALAL mock.  
- Created a bool is_on for each positive and negative channel, at the moment, that is the only variable that should be independent for each channel. Duty, freq and dead_time should be the same in both, so in the constructor, those instance variables point only to the pin_positive address memory, then the pin_negative copies the values.
Also added a DualPWM PinType and defined its struct at Pin.hpp.
=> [FW-59] DualPWM

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
This Dockerfile and  config file allow to use the "Dev Containers" extension in Visual Studio Code to develop ST-LIB inside a container, in which compiler, cmake and all required tools for compiling and developing are already installed and configured.
This only works for compiling and developing ST-LIB in simulator mode. Compiling for STM32 will be investigated in the future
=> [FW-88] Added stuff to allow developing inside a container

Inc/HALAL/Services/Encoder/Encoder.hpp, Inc/HALALMock/Services/Encoder/Encoder.hpp, Src/HALAL/Services/Encoder/Encoder.cpp, Src/HALALMock/Services/Encoder/Encoder.cpp, Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
Implemented a get_delta_clock() function inside Encoder class and adapted EncoderSensor to get the value from there, now:
1. Implemented get_delta_clock(clock_time, last_clock_time) function
- On the HALAL version,makes the same operations as before
- On the HALALMock version, skips the overflow handle as it is not necessary for a simulated  timer
2. Adapted EncoderSensor::read() to get the delta_clock value from Encoder::get_delta_clock()
=> [FW-110] Encoder and EncoderSensor refactor

Inc/HALALMock/Services/Communication/SPI/SPI.hpp
I just change ip and ports declaration so now port is an attribute of Instance, and VMCU IP has a better name.
=> [FW-82] Better IP and ports declaration in SPI mock

Inc/HALALMock/Services/SharedMemory/SharedMemory.hpp, Src/HALALMock/Services/SharedMemory/SharedMemory.cpp
I have overload the start method so you can use the start() and take the one in runes or use start(const char* name) and give a name from the code
=> [FW-116] overload start in shared_memory_gpio and create close functions, improve the class with slight changes

Src/HALAL/Services/InputCapture/InputCapture.cpp, Src/HALALMock/Services/InputCapture/InputCapture.cpp, Tests/InputCaptureTest.cpp
On previous commit I update InputCapture Inscribe to send 0 when it doesn't register the pin, I didn't do it correctly.
Test don't notice the error because shared memory reinit  at each test
=> FIX Inputcapture Inscribe

Src/HALALMock/Services/EXTI/EXTI.cpp, Tests/EXTITest.cpp
Prev exti compare all extis, Inscribed or not inscribed
This throw a segmentation fault if the pin is not inscribed
=> fix_bug_on exti

Src/HALALMock/Services/SharedMemory/SharedMemory.cpp
Added memset at the end of the start methods to clean the SharedMemory, as it had inf from previous executions.
=> Fixed dirty SharedMemory

Inc/HALALMock/Services/Communication/SPI/SPI.hpp, Src/HALALMock/Services/Communication/SPI/SPI.cpp
SPI has been modified to use a command protocol that consists on two commands: SLAVE_SELECT and SLAVE_DESELECT. The first one is sent under the number 1, while the second one is sent under the number 2. If a normal package is sent, it must be preceded by a zero to indicate that there isn't a command and it shouldn't be processed as it.
=> [FW-119] Improve SPI

.github/workflows/c-cpp.yml, Inc/HALAL/HALAL.hpp, Inc/HALALMock/Services/Logger/Logger.hpp, Inc/ST-LIB_LOW/ErrorHandler/ErrorHandler.hpp, Src/HALALMock/Services/Logger/Logger.cpp, Src/ST-LIB_LOW/ErrorHandler/ErrorHandler.cpp, Tests/Runes/SimRunes.cpp
Class used to Log info in simulator mode. You can log in five levels: DEBUG, INFO, WARNING, ERROR and FATAL.
To configure it, you must set in the extern variable config a mask 'oring' the bits that represents what you want.  You can configure which level of logs you want (DEBUG, INFO...), if you want to write logs on the console and/or on a file, and if you want to erase or not the log file.
To use it, you must use one of the five MACROS defined in the hpp file, each one representing the level of the log you want to print. This MACROS are:
- LOG_DEBUG
- LOG_INFO
- LOG_WARNING
- LOG_ERROR
- LOG_FATAL
Also when you call ErrorHandler and you are compiling for simulator, ErrorHandler calls LOG_FATAL by itself, so you don't have to do it
=> [FW-120] Added Logger for simulator mode

Inc/ST-LIB_LOW/Sensors/PWMSensor/PWMSensor.hpp, Inc/ST-LIB_LOW/Sensors/Sensor/Sensor.hpp, Src/ST-LIB_LOW/Sensors/Sensor/Sensor.cpp
PWMSensor inscribed an InputCapture pin but did not include the call to the turn_on() method, so it was not working.
=> [FW-137] Add turn_on() method to PWMSensor

Inc/HALALMock/Services/Communication/SPI/SPI.hpp, Src/HALAL/HALAL.cpp, Src/HALALMock/Services/Communication/SPI/SPI.cpp
All these changes are what I need to do to make SPI works. Yes, I know there are a lot.
- Receiver and sender-receiver threads have been erased, as they weren't needed.
- Receive method is blocking until it is selected and has data to receive.
- Now master can select/deselect simulated slaves, and also slave can be selected by a simulated master (it doesn't work before)
- Several minor fixes.
=> [FW-100] Fixed SPI

Inc/ST-LIB_HIGH/Protections/Boundary.hpp
A check in protections wasn't respecting logical priorities, as C++ doesn't respect them by default, because `and` operation has the most priority. This results as a warning when compiling, preventing compilation with warnings as errors.
=> Fix boundary to respect logical priorities

Inc/HALAL/Services/DigitalOutputService/DigitalOutputService.hpp, Inc/HALALMock/Services/DigitalOutputService/DigitalOutputService.hpp, Inc/ST-LIB_LOW/DigitalOutput/DigitalOutput.hpp, Src/HALAL/Services/DigitalOutputService/DigitalOutputService.cpp, Src/HALALMock/Services/DigitalOutputService/DigitalOutputService.cpp, Src/ST-LIB_LOW/DigitalOutput/DigitalOutput.cpp
The HAL has a method that can lock a GPIO in a certain state until the board resets (using HAL_GPIO_LockPin). This could be useful for the contactors as an example, where once you enter fault you don't want to close them until you reset the board after fixing the fault cause. This is the same for the GD reset and enable, brakes, etc. All driven by a GPIO.
Also I took the chance to run the linter through the digital out code, the logic of this modification is minimal. The interesting methods are named force_lock_state
=> Add pin lock method to digital out

Inc/ST-LIB_LOW/Sensors/LinearSensor/LinearSensor.hpp
A method has been added to LinearSensor class to be able to modify the slope/gain. 
The reason to include it has been to be able to characterize sensors in runtime.
=> Added method to LinearSensor to set slope

Inc/ST-LIB_HIGH/Protections/Boundary.hpp, Inc/ST-LIB_HIGH/Protections/Protection.hpp, Src/ST-LIB_HIGH/Protections/ProtectionManager.cpp
Sorry for the incredible amount of duplicated code, runtime polymorphism and some other abnormalities.
I basically added a frozen value so that that value is sent when the message is issued, this way we ensure integrity with the value that triggered the protection, this is achieved my storing a copy of the value pointed by the pointer.
I also fixed some discrepancies between the high frequency and low frequency protections checks.
I also added individual time tracking for the notification of ProtectionMessages, as otherwise only one would be sent.
I removed some code with test_fault that in the past seemed to indicate whether the Fault was coming from TCP or the board itself, because the naming wasn't clear and the Backend was doing weird stuff with Transport module and connections being …
=> Protections enhancements

Inc/ST-LIB_LOW/Sensors/PWMSensor/PWMSensor.hpp
PWMSensor has a problem in constructor due to bad order. It has been fixed. Y also applied the formatter.
=> Fixed bad-ordered params in PWMSensor

Inc/HALAL/Models/PinModel/Pin.hpp, Inc/HALAL/Services/EXTI/EXTI.hpp, Src/HALAL/Models/PinModel/Pin.cpp, Src/HALAL/Services/EXTI/EXTI.cpp
Mainly there were two problems:
`SensorInterrupt` class lets you register a pin as an EXTI in both edges, but within EXTI class you find hardcoded only Triggers RISING and FALLING. The way to register a Pin as an EXTI in both edges has been added.
The pin class didn't have the proper operation mode to configure a pin as an EXTI in RISING and FALLING edge. This operation mode has also been added
Ah, and I took the opportunity to apply the formatter hehe. The files are small so I hope it won't be a problem to review them.
=> Fixed EXTI

Inc/HALAL/Services/Communication/FDCAN/FDCAN.hpp
Now the can can send 64 bytes per packet instead of 8
=> Fixed fdcan 64 byte sending issue
