- .cproject
- .project
- .settings/language.settings.xml
ST-LIB aun conservaba algunas referencias a Hyperlib y esto causaba warnings, todos los problemas han sido solucionados.
> Referencia a Hyperlib y otros problemas menores solucionados

- .cproject
Include path for clocks, HALAL doesn't compile without it
> add st-lib low to include path

- Inc/HALAL/HALAL.hpp
- Inc/ST-LIB.hpp
- Inc/ST-LIB_LOW/ST-LIB_LOW.hpp
- Src/ST-LIB_LOW/Clocks/Counter.cpp
- Src/ST-LIB_LOW/Clocks/Stopwatch.cpp
Fix of the include path for ST-LIB_LOW
> Fix Include path for ST-LIB_LOW

- Inc/HALAL/Models/LowPowerTimer/LowPowerTimer.hpp
- Inc/HALAL/Models/TimerChannelModel/TimerChannel.hpp
- Inc/HALAL/Services/Communication/SPI/SPI.hpp
- Inc/HALAL/Services/Time/Time.hpp
- Src/HALAL/Models/Runes/Runes.cpp
SPI and Time were lacking include guards, also some models.
> Fix include guards

- Inc/HALAL/Services/Communication/SPI/SPI.hpp
- Inc/HALAL/Services/Communication/UART/UART.hpp
- Inc/ST-LIB.hpp
- Src/HALAL/Models/Runes/Runes.cpp
- Src/HALAL/Services/Communication/SPI/SPI.cpp
- Src/HALAL/Services/Communication/UART/UART.cpp
Añadidos los últimos perifericos a Runes. 
Faltan por añadir los EXTIS.
> Hotfix of the runes.

- Inc/ST-LIB_HIGH/Protections/Protection.hpp
- Inc/ST-LIB_HIGH/Protections/ProtectionManager.hpp
- Inc/ST-LIB_HIGH/ST-LIB_HIGH.hpp
- Src/ST-LIB_HIGH/Protections/Protection.cpp
- Src/ST-LIB_HIGH/Protections/ProtectionManager.cpp
- Implements Protection class that is used to watch over values of variables and implement protections over it, that will trigger whenever the variable don't fullfill its protection expected values
- Implements a ProtectionManager that is a container class for a group of protections and will check if any of the protections triggers and perform actions and notify it whenever happens.
ProtectionHandler can monitor and notify the following variables: name of the variable, value of the variable when triggered, value of the protection expected value, type of the protection and the board that contained the protection.
The ProtectionManager is used as follows:
```cpp
#define BOARD_ID 54
ProtectionManager::set_id(BOARD_ID);
double variable = 5.3;
ProtectionManager_add_protection(&variable, …
```
> Added ProtectionManager

- Inc/HALAL/Services/InputCapture/InputCapture.hpp
- Src/HALAL/Models/Runes/Runes.cpp
This PR adds the updated ADC pins from the IOC
> add ADC pins

- Inc/HALAL/HALAL.hpp
- Inc/ST-LIB_LOW/Actuator/HalfBridge/HalfBridge.hpp
- Inc/ST-LIB_LOW/Actuator/PWM/PWM.hpp
Había algunos includes que tenían mal el nombre y, por tanto, no compilaba.
> Fix include names

- Inc/C++Utilities/CppUtils.hpp
This PR adds cpp20 libraries to be used in the future. I intend to use them on my BMS code, and if it works maybe it can be used on the ST-LIB for future development or refactor.
> add span and ranges

- Inc/HALAL/Services/Communication/UART/UART.hpp
- Src/HALAL/Services/Communication/UART/UART.cpp
This PR fixes UART and updates the implementation to use Spans.
> update UART to use spans

- Inc/C++Utilities/CppUtils.hpp
- Inc/HALAL/Models/PinModel/Pin.hpp
- Inc/HALAL/Services/ADC/ADC.hpp
- Src/HALAL/Models/Runes/Runes.cpp
- Src/HALAL/Services/ADC/ADC.cpp
La dejo a revisar para @ricardochust
> change to unordered_map

- Inc/HALAL/Services/DigitalOutputService/DigitalOutputService.hpp
- Inc/ST-LIB_LOW/Actuator/DigitalOutput/DigitalOutput.hpp
- Inc/ST-LIB_LOW/ST-LIB_LOW.hpp
- Src/HALAL/Services/ADC/ADC.cpp
- Src/HALAL/Services/DigitalOutputService/DigitalOutputService.cpp
- Src/HALAL/Services/EXTI/EXTI.cpp
- Src/HALAL/Services/InputCapture/InputCapture.cpp
- Src/ST-LIB_LOW/Actuator/DigitalOutput/DigitalOutput.cpp
This PR adds DigitalOutput Toggle method. This PR closes #151.
> DigitalOutput Toggle

- Inc/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.hpp
- Src/ST-LIB_LOW/Sensors/EncoderSensor/EncoderSensor.cpp
Se han solucionado varios bugs que habian en el EncoderSensor
> Encoder Fix

- Inc/HALAL/Models/IPV4/IPV4.hpp
- Inc/HALAL/Services/Communication/Ethernet/Ethernet.hpp
- Inc/HALAL/Services/Communication/Ethernet/EthernetNode.hpp
- Inc/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.hpp
- Inc/HALAL/Services/Communication/Ethernet/TCP/Socket.hpp
- Src/HALAL/Services/Communication/Ethernet/Ethernet.cpp
- Src/HALAL/Services/Communication/Ethernet/EthernetNode.cpp
- Src/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.cpp
- Src/HALAL/Services/Communication/Ethernet/TCP/Socket.cpp
> Cambios necesarios para hacer funcionar el ethernet en el template project

- Inc/ST-LIB.hpp
- Src/HALAL/Services/Time/Time.cpp
- Src/ST-LIB.cpp
Este PR deja implementado el ST-LIB update por si queremos congelar la interfaz, la idea es que conforme añadamos update de la state_machine y eso, añadamos cosas al update.
> STLIB update

- Inc/HALAL/Services/Communication/FDCAN/FDCAN.hpp
- Inc/ST-LIB_HIGH/Protections/Protection.hpp
- Src/HALAL/Models/HALconfig/Halconfig.cpp
- Src/HALAL/Services/Communication/FDCAN/FDCAN.cpp
FDCAN config has been configured to make it able to interact with the bootloader.
The clock config has been configured due the same reason.
> Adapted FDCAN for bootloader

- Inc/HALAL/Models/Packets/Packet.hpp
Added Packet Destructor method
> Added Packet Destructor

- Inc/C++Utilities/CppUtils.hpp
- Inc/HALAL/Services/Time/Time.hpp
- Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
- Src/ST-LIB.cpp
- Src/ST-LIB_LOW/StateMachine/StateMachine.cpp
Testcase:
```cpp
#include "main.h"
#include "lwip.h"
#include "ST-LIB.hpp"
#include "Runes/Runes.hpp"
#include "Examples/examples_includes.hpp"
using namespace std::chrono_literals;
extern struct netif gnetif;
int main(void)
{
uint8_t state1 = 0;
uint8_t state2 = 1;
uint8_t state2_1 = 2;
uint8_t state2_2 = 3;
uint8_t state2_3 = 4;
StateMachine general_sm(state1);
general_sm.add_state(state2);
StateMachine specific_sm(state2_1);
specific_sm.add_state(state2_2);
specific_sm.add_state(state2_3);
int contador = 0;
STLIB::start(Nucleo);
printf("Iniciando Testcase State Machine:\n");
general_sm.add_cyclic_action([&](){
printf("Estado 1\n");
}, 100ms, state1);
specific_sm.add_cyclic_action([&](){
printf("Estado 2.1\n");
}, 100ms, state2_1);
specific_sm.add_cyclic_action([&](){
printf("Estado …
```
> Nested state machines

- build.sh
[Screencast from 13-03-23 11:17:50.webm](https://user-images.githubusercontent.com/59616818/224686193-5c9595b2-0608-4b62-8958-94475a5adfc8.webm)
> Build Script 

- Inc/HALAL/Services/ADC/ADC.hpp
- Src/HALAL/Models/DMA/DMA.cpp
- Src/HALAL/Services/ADC/ADC.cpp
This PR fixes Issue where DMA does not work with ETH
TODO: Testing
> clean dma cache

- Inc/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.hpp
- Src/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.cpp
This PR reworks and fixes several bugs of TCP server sockets, same changes are yet to do to TCP client sockets
> Reworked ServerSocket

- Inc/HALAL/Models/Packets/PacketValue.hpp
Fixes the packetvalue destructor issue
> fix packet warning

- .vscode/settings.json
- Src/HALAL/Services/PWM/PhasedPWM/PhasedPWM.cpp
- Src/ST-LIB_LOW/StateMachine/StateMachine.cpp
> ai documentation

- Inc/HALAL/Models/TimerPeripheral/TimerPeripheral.hpp
- Inc/HALAL/Services/Time/Time.hpp
- Src/HALAL/Models/TimerPeripheral/TimerPeripheral.cpp
- Src/HALAL/Services/Time/Time.cpp
Added Mid Resolution Alarms
They share timer with timer23, a guard checks if it is already in use.
It has a precision of 50us, has the same principile of low precision alarms but with a timer that interrupts more frequently
> Added Mid Resolution Alarms

- Inc/ST-LIB_HIGH/Control/Blocks/MatrixMultiplier.hpp
- Inc/ST-LIB_HIGH/ST-LIB_HIGH.hpp
Control Blocks that abstracts Matrix Multiplication
> MatrixMultiplier

- Inc/ST-LIB_LOW/ST-LIB_LOW.hpp
- Inc/ST-LIB_LOW/Sensors/LinearSensor/FilteredLinearSensor.hpp
Linear sensor that performs a moving average on read
> Filtered Linear Sensor

- Inc/ST-LIB_HIGH/Protections/ProtectionManager.hpp
- Inc/ST-LIB_LOW/Sensors/SensorInterrupt/SensorInterrupt.hpp
- Src/ST-LIB_LOW/Sensors/SensorInterrupt/SensorInterrupt.cpp
> Fixed SensorInterrupt and Bug with software integration

- Src/HALAL/HALAL.cpp
- Src/ST-LIB.cpp
Finally switch Ethernet OFF with a simple define
> update Ethernet ifdef guard

- Inc/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.hpp
- Inc/HALAL/Services/Communication/Ethernet/TCP/Socket.hpp
- Src/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.cpp
- Src/HALAL/Services/Communication/Ethernet/TCP/Socket.cpp
Adds an additional constructor that lets you configurate the keepalive on each socket
> Keepalive configuration

- Inc/HALAL/HALAL.hpp
- Inc/HALAL/Services/InfoWarning/InfoWarning.hpp
- Inc/ST-LIB_HIGH/Protections/Boundary.hpp
- Inc/ST-LIB_HIGH/Protections/Protection.hpp
- Src/HALAL/Services/InfoWarning/InfoWarning.cpp
- Src/ST-LIB_HIGH/Protections/ProtectionManager.cpp
yet to be tested, invoke using WARNING()
> add WARNING, just like ErrorHandler

- Src/HALALMock/Services/DigitalOutputService/DigitalOutputService.cpp
DigitalOutputService for Halal_Mock
> DigitalOutputService for Halal_Mock

- Inc/HALALMock/Services/Time/RTC.hpp
- Src/HALALMock/Services/Time/RTC.cpp
RTC module is used by ErrorHandler and Boundary for issuing the messages.
> RTC module

- README.md
- setup.env
I think the addition of a setup file is necessary to ensure the correct environment setting of the workspace now that things are going to start to run natively, I just created the template file
> Added setup file

- Src/HALALMock/Services/Communication/FDCAN/FDCAN.cpp
Cant use push --force so here we are
> Fixed simple error in FDCAN

- Inc/HALALMock/Services/Communication/Ethernet/Ethernet.hpp
- Inc/HALALMock/Services/Communication/Ethernet/TCP/ServerSocket.hpp
- Inc/HALALMock/Services/Communication/Ethernet/TCP/Socket.hpp
- Inc/HALALMock/Services/Communication/Ethernet/UDP/DatagramSocket.hpp
- Src/HALALMock/Models/IPV4/IPV4.cpp
- Src/HALALMock/Services/Communication/Ethernet/Ethernet.cpp
- Src/HALALMock/Services/Communication/Ethernet/TCP/ServerSocket.cpp
- Src/HALALMock/Services/Communication/Ethernet/TCP/Socket.cpp
- Src/HALALMock/Services/Communication/Ethernet/UDP/DatagramSocket.cpp
The idea of this module is to replicate HALAL ethernet module.
> [FW-102] Tested simulator ethenet module

- README.md
I have just updated the README so that a person who doesn't know how to use this project can read it and know how to install everything they need.
> [FW-141] Update README

- Inc/HALALMock/Services/SharedMemory/SharedMemory.hpp
- Inc/ST-LIB_LOW/StateMachine/StateMachine.hpp
- Src/HALALMock/Services/SharedMemory/SharedMemory.cpp
- Src/ST-LIB_LOW/StateMachine/StateMachine.cpp
Small changes to abstract the use of the statemachine sharedmemory
> FW[134] Added statemachine shm functions

- .devcontainer/Dockerfile
- .github/workflows/c-cpp.yml
This PR fixes the github actions sudden breaking change where the code would compile in the local machine but not in the actions.
> [WIP] [FW-170] Fix github actions not compiling

- Inc/HALALMock/Services/Communication/Ethernet/TCP/ServerSocket.hpp
- Src/HALALMock/Services/Communication/Ethernet/Ethernet.cpp
- Src/HALALMock/Services/Communication/Ethernet/TCP/ServerSocket.cpp
- Src/HALALMock/Services/Communication/Ethernet/TCP/Socket.cpp
- Src/HALALMock/Services/Communication/Ethernet/UDP/DatagramSocket.cpp
- Src/HALALMock/Services/SharedMemory/SharedMemory.cpp
It has been modified some mocks to use the new Logger instead of using ErrorHandler/cout. Also the linter has been applied on some sources.
> [FW-126] Use Logger 

- Inc/HALALMock/Services/Communication/FDCAN/FDCAN.hpp
- Src/HALALMock/Services/Communication/FDCAN/FDCAN.cpp
Does not compile, so i fixed it ^^
> Fix fdcan2

- README.md
Test for Jira automations and a small update to the readme
> [FW-304] This PR is a test for Jira automations

- Inc/HALALMock/Models/PinModel/Pin.hpp
- Src/HALALMock/Services/Communication/FDCAN/FDCAN.cpp
Added a is_on variable to the mocked pin so it doesnt explode when using the simulator.
> Add is_on to the mocked fdcan

- Inc/HALAL/Services/Watchdog/Watchdog.hpp
- Inc/ST-LIB.hpp
- Src/HALAL/HALAL.cpp
- Src/HALAL/Services/Watchdog/Watchdog.cpp
- Src/ST-LIB.cpp
> [FW-344] Watchdog

- Src/HALAL/HALAL.cpp
- Src/ST-LIB.cpp
Add a flag to debug and move the watchdog::start after ethernet::start
> Watchdog changes

- Inc/HALAL/HALAL.hpp
- Inc/HALAL/Models/MAC/MAC.hpp
- Inc/HALAL/Services/Communication/Ethernet/Ethernet.hpp
- Inc/HALALMock/Models/MAC/MAC.hpp
- Inc/HALALMock/Services/Communication/Ethernet/Ethernet.hpp
- Inc/ST-LIB.hpp
- LWIP/Target/ethernetif.c
- Src/HALAL/HALAL.cpp
- Src/HALAL/Models/MAC/MAC.cpp
- Src/HALAL/Services/Communication/Ethernet/Ethernet.cpp
- Src/HALALMock/Models/MAC/MAC.cpp
- Src/HALALMock/Services/Communication/Ethernet/Ethernet.cpp
- Src/ST-LIB.cpp
Add a new parameter to ST-LIB start to configure the MAC address and prevent collisions.
> [FW 372] Configurable MAC address

- Inc/ST-LIB_HIGH/Protections/ProtectionManager.hpp
- Src/ST-LIB_HIGH/Protections/ProtectionManager.cpp
- Src/ST-LIB_LOW/ErrorHandler/ErrorHandler.cpp
the error handler message will be send every 1 second
> Hotfix_ProtectionManager_Notification

- Src/HALAL/Services/Communication/FDCAN/FDCAN.cpp
- Src/ST-LIB_HIGH/Protections/ProtectionManager.cpp
> Send fault by Can

- Inc/HALAL/Models/PinModel/Pin.hpp
> Make a little change so the enums are for sure uint8_T PInState and Trigger

- Inc/HALAL/Models/Packets/Order.hpp
- Inc/HALAL/Services/Communication/Ethernet/TCP/Socket.hpp
- Src/HALAL/Services/Communication/Ethernet/TCP/ServerSocket.cpp
- Src/HALAL/Services/Communication/Ethernet/TCP/Socket.cpp
This is a little feature to know the ip, of the order that sent the order
> New feature
